# Generated by Django 4.0.4 on 2022-05-08 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_fact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='month',
            field=models.CharField(choices=[('January', 1), ('February', 2), ('March', 3), ('April', 4), ('May', 5), ('June', 6), ('July', 7), ('August', 8), ('September', 9), ('October', 10), ('November', 11), ('December', 12)], max_length=60, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
